// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx'
import * as $_500 from './routes/_500.tsx'
import * as $_app from './routes/_app.tsx'
import * as $_middleware from './routes/_middleware.ts'
import * as $blog_slug_ from './routes/blog/[slug].tsx'
import * as $blog_index from './routes/blog/index.tsx'
import * as $index from './routes/index.tsx'
import * as $sitemap_xml from './routes/sitemap.xml.ts'
import * as $works_slug_ from './routes/works/[slug].tsx'
import * as $copy_code from './islands/copy-code.tsx'
import * as $mobile_menu from './islands/mobile-menu.tsx'
import * as $socialmedia_share from './islands/socialmedia-share.tsx'
import * as $theme_toggle from './islands/theme-toggle.tsx'
import { type Manifest } from '$fresh/server.ts'

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_500.tsx': $_500,
    './routes/_app.tsx': $_app,
    './routes/_middleware.ts': $_middleware,
    './routes/blog/[slug].tsx': $blog_slug_,
    './routes/blog/index.tsx': $blog_index,
    './routes/index.tsx': $index,
    './routes/sitemap.xml.ts': $sitemap_xml,
    './routes/works/[slug].tsx': $works_slug_,
  },
  islands: {
    './islands/copy-code.tsx': $copy_code,
    './islands/mobile-menu.tsx': $mobile_menu,
    './islands/socialmedia-share.tsx': $socialmedia_share,
    './islands/theme-toggle.tsx': $theme_toggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
